version: '3.6'
services:
    jenkins-blue:
        container_name: jenkins-docker
        image: jenkins-blue
        build:
            context: .
        volumes:
            - ./jenkins-docker-certs:/certs/client
            - ./jenkins-data:/var/jenkins_home
        ports:
            - 3000:3000
            - 2376:2376
            - 8085:8080
            - 50000:50000
        environment:
            - DOCKER_HOST=tcp://jenkins-blue:2376
            - DOCKER_CERT_PATH=/certs/client
            - DOCKER_TLS_VERIFY=1
            - DOCKER_TLS_CERTDIR=/certs
networks:
    default:
        name: jenkins
        external: true
